### PR TITLE
Update go.mod for alternate plugin

### PR DESCRIPTION
**Pull request by UladzimirTrehubenka**

### CODE REVIEW

**Comment by UladzimirTrehubenka** [comment]
@miekg Sorry, but https://github.com/coredns/alternate/pull/9 was a little bit broken - this is the fix.

**Comment by miekg** [comment]
Can someone else deal with this repo?

**Comment by UladzimirTrehubenka** [comment]
Previously @fturib and @johnbelamaric have been responsible for it as I understand.

**Comment by johnbelamaric** [comment]
Someone at Infoblox should do it, maybe @chrisohaver or @rajansandeep ?

**Pull request merged**
