### PR TITLE
Support passing in multiple DNS rcodes in single alternate block

### PR DESCRIPTION
**Pull request by andrewlouis93**
Fixes https://github.com/coredns/alternate/issues/12

### CODE REVIEW

**Comment by andrewlouis93** [comment]
@chrisohaver please take a look whenever you get some time, thanks!

**Comment by UladzimirTrehubenka** [comment]
@andrewlouis93 Could you please finalize the PR (because we also interested in it)?

**Comment by andrewlouis93** [comment]
Thanks for the review @chrisohaver - let me know if the syntax and examples section look sound to you?

**Comment by andrewlouis93** [comment]
Thank _you_ @chrisohaver for making contributing here so smooth :)

**Pull request merged**
